locations:
  18th_Crs_BsStp_JN_FIX_1:
    camera_number: 4935
    site_id: 952
    directions:
      north:
        line:
          x1: 500
          y1: 390
          x2: 1600
          y2: 280
        text:
          x1: 450
          y1: 430
        result:
          x1: 100
          y1: 100
          offset: 20
  18th_Crs_BsStp_JN_FIX_2:
    camera_number: 4936
    site_id: 952
    directions:
      south:
        line:
          x1: 1150
          y1: 250
          x2: 1430
          y2: 320
        text:
          x1: 1450
          y1: 330
        result:
          x1: 1650
          y1: 100
          offset: 20
      north:
        line:
          x1: 650
          y1: 250
          x2: 870
          y2: 320
        text:
          x1: 550
          y1: 250
        result:
          x1: 100
          y1: 100
          offset: 20