# -*- coding: utf-8 -*-
"""Modified_YOLOv8_adding_a_head.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmTyEMlNH9p9Td-BMGYOyij5Aqg4Z_xu

> **WARNING**
>
> Don't use "Run All". Run the cells one after another manually.
"""

#!rm -rf /content/datasets

#!rm -rf /content/ultralytics

#! gdown --id 14nMYyaLMEQpNqC-73mcJ3Q-r0_yfTMdj

#!getcwd

!git clone https://github.com/ultralytics/ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/ultralytics

!git reset --hard 2071776a3672eb835d7c56cfff22114707765ac

# Download patch
!wget https://gist.githubusercontent.com/Y-T-G/8f4fc0b78a0a559a06fe84ae4f359e6e/raw/17b1407fefeac86d089c4cf14f174c8bb44948af/add_head.patch

!git apply add_head.patch

!pip install -e .

from google.colab import drive
drive.mount('/content/drive')

#datafile_colabpath='/content/drive/MyDrive/MobilityChallenge/Roboflow_AutoTempoDataset.v1i.yolov8_UpdatedYAML.zip'
datafile_colabpath='/content/drive/MyDrive/MobilityChallenge/Roboflow_AutoTempoDataset.v1i.yolov8_UpdatedYAML'

#from zipfile import ZipFile
#with ZipFile(datafile_colabpath, 'r') as zip:
#with ZipFile('/content/SmallRoboflow_AutoTempoDataset.v1i.yolov8_UpdatedYAML.zip', 'r') as zip:
#  zip.extractall()

#!pip install roboflow
#from roboflow import Roboflow
#rf = Roboflow(api_key="TfSfBFJ6wzNbaqKgZWsD")
#project = rf.workspace("vehiclesdata").project("dataclusterautotempodataset")

#version = project.version(1)
#dataset = version.download("yolov8")
#!mkdir -p /content/datasets/Project-1
#!mv DataClusterAutoTempoDataset-1/** /content/datasets/Project-1
#!mv /content/datasets/Project-1/data.yaml /content/datasets

"""# Train a model with frozen COCO backbone"""

#The above code is required if we are directly importing dataset from Roboflow
#While importing, Roboflow installs its own version of ultralytics. To remove this version the below code is required
# Reset runtime
#import IPython
#IPython.Application.instance().kernel.do_shutdown(True)

# Wait for restart and then continue

"""> **WARNING**
>
> Wait for the Colab kernel to crash and restart after running the above cell, before continuing.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/ultralytics

from ultralytics import YOLO
import torch
import copy

model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

org_class_list = model.names
org_class_list

# Keep a copy of old state dict for sanity check
old_dict = copy.deepcopy(model.state_dict())

# We should freeze all but the last layer
model.state_dict().keys()

# Add a callback to put the frozen layers in eval mode to prevent BN values
# from changing.
def put_in_eval_mode(trainer, n_layers=22):
  for i, (name, module) in enumerate(trainer.model.named_modules()):
    if name.endswith("bn") and int(name.split('.')[1]) < n_layers:
      module.eval()
      module.track_running_stats = False
      # print(name, " put in eval mode.")

model.add_callback("on_train_epoch_start", put_in_eval_mode)
model.add_callback("on_pretrain_routine_start", put_in_eval_mode)

# Train the model. Freeze the first 22 layers [0-21].
yamlFile = "/content/drive/MyDrive/MobilityChallenge/Roboflow_AutoTempoDataset.v1i.yolov8_UpdatedYAML/data.yaml"
#results = model.train(data='/content/SmallRoboflow_AutoTempoDataset.v1i.yolov8_UpdatedYAML/data.yaml', freeze=22, epochs=100, imgsz=640)
results = model.train(data=yamlFile, freeze=22, epochs=100, imgsz=640)

model.names

def compare_dicts(state_dict1, state_dict2):
    # Compare the keys
    keys1 = set(state_dict1.keys())
    keys2 = set(state_dict2.keys())

    if keys1 != keys2:
        print("Models have different parameter names.")
        return False

    # Compare the values (weights)
    for key in keys1:
        if not torch.equal(state_dict1[key], state_dict2[key]):
            print(f"Weights for parameter '{key}' are different.")
            if "bn" in key and "22" not in key:
              state_dict1[key] = state_dict2[key]

# Compare the dicts. Changes should only be in layer 21 and above
compare_dicts(old_dict, model.state_dict())

new_state_dict = dict()

model.state_dict().items()

#  Increment the head number by 1 in the state_dict
for k, v in model.state_dict().items():
  if k.startswith("model.model.22"):
    new_state_dict[k.replace("model.22", "model.23")] = v
  # else:
  #   new_state_dict[k] = v

# Save the current state_dict
torch.save(new_state_dict, "yolov8n_lp.pth")



"""# Create new architecture with extra head and load custom weights"""

from ultralytics import YOLO
import torch

model_2 = YOLO('ultralytics/cfg/models/v8/yolov8n-2xhead.yaml', task="detect").load('yolov8n.pt')

model_2.names

model_2.state_dict().keys()

state_dict = torch.load("yolov8n_lp.pth")

state_dict.keys()

# Load state_dict of the custom trained model head. Layer 23.
model_2.load_state_dict(state_dict, strict=False)

model_2.names

new_names = model.names
new_names

org_names = org_class_list
org_names

newkey = 0
for k, v in new_names.items():
    if newkey == 0:
        newkey = len(org_names)
    else:
        newkey = newkey+1
    org_names[newkey] = new_names[k]
print(org_names)

model_2.model.names = org_names
model_2.names

model_2.ckpt = {"model": model_2.model}
model_2.save("Best_AutoTempoDataset_v0.1.pt")

# Output of COCO model
model_coco = YOLO("yolov8n.pt")

# For consistency
model_coco.model.names = {k:k for k in model_coco.names.keys()}

result_coco = model_coco.predict("/content/Roboflow_AutoTempoDataset.v1i.yolov8/valid/images/20210427_22_52_25_000_Db2I2d17GLf53JzlQRSP28hD4Ml1_F_2592_1944_jpg.rf.6f3fc57c8d5ea389e33e25a701cf07a1.jpg")[0]



# Output of custom LP model
model_lp = YOLO("/content/ultralytics/Best_AutoTempoDataset_v0.1.pt")

# For plotting consistency, change all class names to class numbers
model_lp.model.names = {k:k for k in model_lp.names.keys()}

result_lp = model_lp.predict("/content/Roboflow_AutoTempoDataset.v1i.yolov8/valid/images/20210427_22_52_25_000_Db2I2d17GLf53JzlQRSP28hD4Ml1_F_2592_1944_jpg.rf.6f3fc57c8d5ea389e33e25a701cf07a1.jpg")[0]

print(model_lp.names)
print(model_coco.names)

# Output of the new model
#result_merged = model_2.predict("test.jpg")[0]

import matplotlib.pyplot as plt
import numpy as np

def show_output(images):
    image = np.vstack(images)
    fig = plt.figure()
    ax = plt.Axes(fig, [0., 0., 1., 1.])
    ax.set_axis_off()
    fig.add_axes(ax)
    fig.set_size_inches((5,15))
    ax.imshow(image[...,::-1])

show_output([result_coco.plot(), result_lp.plot(), result_merged.plot()])

